"""Reject AI attribution and assistant session links in commit messages.

This repository publishes architecture from an employer system under my own name. A commit
message that credits an assistant, or links back to an assistant session, is a claim about
authorship in a place where authorship is the whole point -- and unlike a file, a pushed commit
message cannot be corrected without rewriting published history.

The rule is narrow on purpose, and the narrowness is the design rather than a compromise:

  matched      a session link anywhere in the message; a trailer whose NAME asserts machine
               authorship; a trailer whose VALUE names an assistant; an attribution sentence
  not matched  prose. The message may name an assistant, a vendor or this policy itself,
               which the sibling repository's history does in several commits

A checker that flags the word "Claude" would fail an honest commit explaining this file, and
the usual response to a guard that cries wolf is to delete the guard.

Range, not history. New commits are checked, not every commit ever made. A single bad message
that reaches a published branch would otherwise fail every future build on something nobody
can fix without a force push. This repository's history is clean as of 13 Sep 2026, verified
with --all; the range default is about what happens after that stops being true.

Usage:
    python tools/check_commit_messages.py                 # commits not on the upstream branch
    python tools/check_commit_messages.py <range>         # an explicit range
    python tools/check_commit_messages.py --all           # every commit on every ref
    python tools/check_commit_messages.py --msg <file>    # one message, for a commit-msg hook
"""

from __future__ import annotations

import re
import subprocess
import sys

# A link back to an assistant session. Unambiguous machine output: nobody writes one in prose,
# so it is matched anywhere in the message.
SESSION = re.compile(
    r"claude\.ai/code/session|https?://[a-z0-9.-]+/code/session_|/session_[A-Za-z0-9]{16,}",
    re.IGNORECASE,
)

# Trailer NAMES that are prohibited whatever they carry. A trailer is a structured assertion
# about how the commit came to exist, so the name alone is the violation. "Co-authored-by" is
# deliberately absent: a human co-author is legitimate, and it is checked by value below.
TRAILER_NAME = re.compile(
    r"^\s*(claude-session|[a-z]+-session|generated-by|generated-with|ai-generated|model|assistant)\s*:",
    re.IGNORECASE,
)

# Trailer VALUES that name an assistant, for the trailers a human may legitimately use.
TRAILER_VALUE = re.compile(
    r"^\s*(co-authored-by|signed-off-by|assisted-by|created-by|authored-with)\s*:(?P<value>.*)$",
    re.IGNORECASE,
)
ASSISTANT = re.compile(
    r"claude|anthropic|copilot|chatgpt|openai|gpt-[0-9]|gemini|\bai[ -]assistant\b|\bbot\b",
    re.IGNORECASE,
)

# Attribution sentences. Anchored to "generated by/with <assistant>" and to a standalone
# AI-generated claim, so a message may still say a page must not look AI-generated.
ATTRIBUTION = re.compile(
    r"generated (by|with) (claude|chatgpt|copilot|gemini|an? ai\b|anthropic|openai)"
    r"|^\s*(this (commit|change) (is|was) )?ai-generated\s*\.?\s*$",
    re.IGNORECASE,
)

GUIDANCE = """
A commit message asserts AI authorship or links an assistant session.

Rewrite the message rather than the identity:
  git commit --amend                    # for the most recent commit
  git rebase -i <base>                  # reword an older one, if it is unpushed

Only the message is read. Prose that discusses an assistant, a vendor, or this policy is
unaffected -- what fails is a trailer or a session link.
"""


def violations(message: str) -> list[str]:
    """Every line of one message that breaks the policy."""
    found = []
    for line in message.splitlines():
        line = line.rstrip("\r")
        if SESSION.search(line):
            found.append(f"assistant session link: {line.strip()}")
        elif TRAILER_NAME.match(line):
            found.append(f"prohibited attribution trailer: {line.strip()}")
        elif ATTRIBUTION.search(line):
            found.append(f"AI attribution statement: {line.strip()}")
        else:
            trailer = TRAILER_VALUE.match(line)
            if trailer and ASSISTANT.search(trailer.group("value")):
                found.append(f"AI attribution trailer: {line.strip()}")
    return found


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True, encoding="utf-8"
    ).stdout


def resolve_range(argv: list[str]) -> str:
    if argv and argv[0] == "--all":
        return "--all"
    if argv:
        return argv[0]
    try:
        upstream = git("rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}").strip()
        return f"{upstream}..HEAD"
    except subprocess.CalledProcessError:
        return "HEAD"


def main() -> int:
    argv = sys.argv[1:]

    if argv and argv[0] == "--msg":
        if len(argv) < 2:
            print("FAIL --msg needs a message file", file=sys.stderr)
            return 2
        try:
            raw = open(argv[1], encoding="utf-8").read()
        except OSError as error:
            print(f"FAIL cannot read the message file: {error}", file=sys.stderr)
            return 2
        # Git's comment lines never reach the stored message.
        body = "\n".join(line for line in raw.splitlines() if not line.startswith("#"))
        found = violations(body)
        if not found:
            return 0
        for problem in found:
            print(f"FAIL {problem}", file=sys.stderr)
        print(GUIDANCE, file=sys.stderr)
        return 1

    revs = resolve_range(argv)

    # A range that does not resolve must not read as "nothing to check". Silent success is the
    # one result a guard may not produce.
    try:
        shas = git("rev-list", revs).split()
    except subprocess.CalledProcessError:
        print(f"FAIL cannot resolve revision range: {revs}", file=sys.stderr)
        print("     Nothing was checked. Pass a range that exists, or --all.", file=sys.stderr)
        return 2

    failed = False
    for sha in shas:
        message = git("log", "-1", "--format=%B", sha)
        for problem in violations(message):
            print(f"FAIL {sha[:9]} {problem}")
            failed = True

    if failed:
        print(GUIDANCE)
        return 1

    print(f"commit messages clean: {len(shas)} commit(s) checked in {revs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
